# Generated by Django 3.1.5 on 2021-01-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newGround', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='New Ground', max_length=255),
        ),
    ]
